// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"schedulii/src/db"
	"schedulii/src/handlers/data_handler"
	"schedulii/src/models"
	"schedulii/src/models/data_model"
	"schedulii/src/repositories"
	"schedulii/src/routes"
	"schedulii/src/services/data_srv"
)

// Injectors from wire.go:

func InitializeApp() (ScheduliiApp, error) {
	pool, err := db.NewDatabaseConnection()
	if err != nil {
		return ScheduliiApp{}, err
	}
	engine := gin.Default()
	userRepository := repositories.NewUserRepository(pool)
	userService := data_srv.NewUserService(userRepository)
	userHandler := data_handler.NewUserHandler(userService)
	eventRepository := repositories.NewEventRepository(pool)
	eventService := data_srv.NewEventService(eventRepository)
	eventHandler := data_handler.NewEventHandler(eventService)
	groupRepository := repositories.NewGroupRepository(pool)
	groupService := data_srv.NewGroupService(groupRepository)
	groupHandler := data_handler.NewGroupHandler(groupService)
	router := routes.NewRouter(engine, userHandler, eventHandler, groupHandler)
	scheduliiApp := NewScheduliiApp(pool, engine, router)
	return scheduliiApp, nil
}

// wire.go:

var AppSet = wire.NewSet(db.NewDatabaseConnection, gin.Default, repositories.NewEventRepository, wire.Bind(new(models.Repository[data_model.Event]), new(*repositories.EventRepository)), data_srv.NewEventService, data_handler.NewEventHandler, repositories.NewGroupRepository, data_srv.NewGroupService, data_handler.NewGroupHandler, repositories.NewUserRepository, data_srv.NewUserService, data_handler.NewUserHandler, routes.NewRouter, NewScheduliiApp)
