// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"schedulii/src/db"
	"schedulii/src/handlers"
	"schedulii/src/models"
	"schedulii/src/repositories"
	"schedulii/src/routes"
	"schedulii/src/services"
)

// Injectors from wire.go:

func InitializeApp() (ScheduliiApp, error) {
	pool, err := db.NewDatabaseConnection()
	if err != nil {
		return ScheduliiApp{}, err
	}
	engine := gin.Default()
	userRepository := repositories.NewUserRepository(pool)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	eventRepository := repositories.NewEventRepository(pool)
	eventService := services.NewEventService(eventRepository)
	eventHandler := handlers.NewEventHandler(eventService)
	groupRepository := repositories.NewGroupRepository(pool)
	groupService := services.NewGroupService(groupRepository)
	groupHandler := handlers.NewGroupHandler(groupService)
	router := routes.NewRouter(engine, userHandler, eventHandler, groupHandler)
	scheduliiApp := NewScheduliiApp(pool, engine, router)
	return scheduliiApp, nil
}

// wire.go:

var AppSet = wire.NewSet(db.NewDatabaseConnection, gin.Default, repositories.NewEventRepository, wire.Bind(new(models.Repository[models.Event]), new(*repositories.EventRepository)), services.NewEventService, handlers.NewEventHandler, repositories.NewGroupRepository, wire.Bind(new(models.Repository[models.Group]), new(*repositories.GroupRepository)), services.NewGroupService, handlers.NewGroupHandler, repositories.NewUserRepository, wire.Bind(new(models.Repository[models.User]), new(*repositories.UserRepository)), services.NewUserService, handlers.NewUserHandler, routes.NewRouter, NewScheduliiApp)
