apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedulii-persistent-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schedulii-postgres
spec:
  serviceName: schedulii-postgres
  selector:
    matchLabels:
      app: schedulii-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: schedulii-postgres
    spec:
      containers:
        - name: schedulii-postgres
          image: postgres:16.1
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-data
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: schedulii-persistent-volume-claim
        - name: init-data
          projected:
            sources:
              - configMap:
                  name: schedulii-postgres-schema
              - configMap:
                  name: schedulii-postgres-preload-data

---
apiVersion: v1
kind: Service
metadata:
  name: schedulii-postgres-service
spec:
  selector:
    app: schedulii-postgres
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
