apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulii-api-deployment
  labels:
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schedulii-api
  template:
    metadata:
      labels:
        app: schedulii-api
    spec:
      containers:
        - name: schedulii-api-pod
          image: docker.io/library/schedulii_api
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql://postgres@schedulii-postgres-service

---
apiVersion: v1
kind: Service
metadata:
  name: schedulii-api-service
spec:
  selector:
    app: schedulii-api
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: schedulii-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: schedulii.api.dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: schedulii-api-service
                port:
                  number: 9000
