name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.9.2

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
        if: github.ref != 'refs/heads/main'

      # echo ${{ secrets.DATABASE_URL }} > .env
      # echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres" > .env
      # set SQLX_OFFLINE=true so that sqlx doesn't attempt to connect to the DATABASE_URL
      - name: Setup environment variables
        run: |
          touch .env
          echo "SQLX_OFFLINE=true" > .env
          cat .env

      - name: Verify Database Schema
        run: |
          cargo install sqlx-cli --no-default-features --features postgres
          cargo sqlx prepare --check --workspace

      - name: Run (Format, Lint, Test, Build) Checks
        run: npx nx affected -t fmt,lint,test,build --parallel=3
        env:
          GITHUB_TOKEN: ${{ secrets.DATABASE_URL }}
