name: Semantic Versioning
on:
  push:
    branches:
      - 'main'
      - 'erickexinlu-patch-1'

jobs:
  tag_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Github Tag with semantic versioning
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
